### PR TITLE
Update kovan spec for Istanbul

### PR DESCRIPTION
**Pull request by phahulin**
Reference in parity repository
https://github.com/paritytech/parity-ethereum/commit/2627288311e952ff3b6b9675dfeda24f75b8249e

Kovan HF is about to be activated at block `14111141` (~`Sunday, 13-Oct-19 08:35 UTC`)

### CODE REVIEW

**Comment by phahulin** [comment]
Needs to be tested when parity version with Istanbul is actually released

**Comment by varasev** [comment]
> Needs to be tested when parity version with Istanbul is actually released

Doesn't v2.6.3-beta support Istanbul already? Or it is not fully supported yet?

**Comment by phahulin** [comment]
As I understand 2.6.3 has support for Istanbul but doesn't set any HF activation dates. They are set in https://github.com/paritytech/parity-ethereum/pull/11068 which is not released yet.

**Comment by phahulin** [comment]
In the recently released [parity 2.6.4](https://github.com/paritytech/parity-ethereum/releases) this spec is accepted and starts to sync, so this PR is ready for review

**Comment by varasev** [comment]
I've compared https://github.com/paritytech/parity-ethereum/blob/v2.6.4/ethcore/res/ethereum/kovan.json with https://github.com/poanetwork/poa-chain-spec/blob/phahulin-patch-1/spec.json

It seems we have differences in the next sections of the spec:

- `hardcodedSync.header`
- `hardcodedSync.totalDifficulty`
- `hardcodedSync.CHTs`

Parity's `kovan.json` has

`hardcodedSync.header` = `f90247a0d0c0f490e8e5045fa96fd77ce45ed983900feaab964b2b0ba3a2d3a6b5e0f842a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d493479400d6cc1ba9cf89bd2e58009741f4f7325badc0eda0c91e59c81193c4fead4f64ecaa349e97056409dfbb787772ea3c1e55e7582b2ea08be1332f5e7eac286c7e5e5ccf3760e47f4a919548c15e748ad4351bb8405f9aa054e0533aa3433f4d07afa226230c867fc1e2844b5f49b25aba8df17630d9f8c8b901000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000090fffffffffffffffffffffffffffffffe83a26801837a12008306f78d845c9da0b09fde830203088f5061726974792d457468657265756d86312e33332e30827769841727682cb841d6db93a25c84287603ee26e48db0dd301753840cc7283d411d3febd0485e02b2520086bebfb3aec1ab69403f45f0d59249bf0d458f33aa268dc4badefc73c8d300`

`hardcodedSync.totalDifficulty` = `3571337622391237938633151520660827524104528124`

Our `spec.json` has

`hardcodedSync.header` = `f90247a0053fd336e39af5f535a13b7d5d5de48a3288894e5c30ef3c200ef960604ae460a01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d4934794596e8221a30bfe6e7eff67fee664a01c73ba3c56a09bf41200496ce2f3f27d2ca493d3fc12a99ad3f86bcd0a5efbcbc763cce534dea0828e82d29bdc7fb6589d86190882a992526f1fe446c8ae3d3c35a77f154d1594a044bfdadad40cbd7c22b59cffdb86ec538447a9105604bcd2fdc71fe8881dd72bb90100000000000300000000000040010000080000000000000000400000000a000000040000400000000000000000000000000000000000000000000100000000000000020000000000000000000800000000000000000000000000002000020002000000000020000000080008000000000200000002040000000000001000000000000000000000000000000000000000000000002000000000000100004020000000000000000000000000000001000400000000000000800080000080008004000000000200000400000000000200000080000100000000010000800000000000000010000000000000000020000000000000000000004000000000000000000090fffffffffffffffffffffffffffffffe83cd7801837a12008308dafe845d7b683c9fde830205058f5061726974792d457468657265756d86312e33362e30826c6984175eda0fb841df67463557c0bceee7f98a615935454b5367183c12cf93717997624523cf40b8275f59ea2eef0af2b8baabf613216378149891e1a6bdc6497e18865ca325977800`

`hardcodedSync.totalDifficulty` = `4531663462502962897665533388776747591449354009`

And our has much more items in the `hardcodedSync.CHTs`.

The diff file is attached: [diff.txt](https://github.com/poanetwork/poa-chain-spec/files/3663320/diff.txt)

**Comment by phahulin** [comment]
Thanks for noticing. According to docs those values are used by light-clients, so I suppose we can copy them from parity repo.

**Review by varasev — APPROVED** [review]
OK, now the files are identical.

**Review by igorbarinov — APPROVED** [review]

**Pull request merged**
