### PR TITLE
(Sokol) Update spec for Istanbul

### PR DESCRIPTION
**Pull request by varasev**
The `Istanbul HF` in `Sokol` is about to be activated at block `12095200` (~`Thursday, 05-Dec-19 11:00 UTC`).

The corresponding PR in Parity repository: https://github.com/paritytech/parity-ethereum/pull/11282

This HF requires updating nodes to `Parity v2.6.5`.

~Before updating validator nodes, we need to test the launching of `Parity v2.6.5` with the proposed `spec.json` since its format is changed in that version:~  ~https://github.com/paritytech/parity-ethereum/pull/11039~ (done)

### CODE REVIEW

**Comment by varasev** [comment]
~I'm trying to launch Parity with `parity --chain ~/poa-chain-spec/spec.json --reserved-peers ~/poa-chain-spec/bootnodes.txt --base-path ~/tests/test-sokol-new-spec --jsonrpc-cors all` but cannot find any peers. My firewall is turned off.~

~The same goes for `parity --chain poasokol --base-path ~/tests/test-sokol-new-spec --jsonrpc-cors all`.~

(Fixed in https://github.com/poanetwork/poa-chain-spec/pull/129)

**Comment by phahulin** [comment]
Is it correct that `eip1108_transition`s are removed?

**Comment by varasev** [comment]
> Is it correct that `eip1108_transition`s are removed?

Yes: https://github.com/paritytech/parity-ethereum/pull/11039/files?file-filters%5B%5D=.json#diff-0884992219f0c9ad9d296881ebacd29f

**Comment by varasev** [comment]
I've just successfully tested the same transition with https://github.com/varasev/test-block-reward on `Parity v2.6.5`.

See the latest commit: https://github.com/varasev/test-block-reward/commit/59d56ee4a782083d394c9b6d352eaa04ec18468d

**Comment by varasev** [comment]
@phahulin If you don't see any concerns here, please, let me know and I'll do the same changes for https://github.com/paritytech/parity-ethereum/blob/master/ethcore/res/ethereum/poasokol.json

**Review by phahulin — APPROVED** [review]

**Comment by varasev** [comment]
The corresponding PR in Parity's repo: https://github.com/paritytech/parity-ethereum/pull/11282

**Review by igorbarinov — APPROVED** [review]

**Pull request merged**
