### PR TITLE
(Update) ABIs and addresses of contracts for Sokol

### PR DESCRIPTION
**Pull request by vbaranov**
- `contracts.json` instead of `contracts.txt` to use in DApps and scripts
- names of ABI files, as from [script](https://github.com/poanetwork/poa-network-consensus-contracts/blob/master/scripts/getABI.js)

### CODE REVIEW

**Comment by phahulin** [comment]
And drop the `_ADDRESS` suffix where not part of the contract name (e.g. `PoaNetworkConsensus`)

**Comment by vbaranov** [comment]
@phahulin we have a structure like `VOTING_TO_CHANGE_PROXY_ADDRESS` in all 3 DApps. We use only `keyManager` contract in scripts. It seems it will be simpler to change 1 contract name in 2 scripts, than 8 contract names in 3 DApps. Or I miss something and are any other doubts about naming?

**Comment by phahulin** [comment]
OK, still some names (`VOTING_TO_CHANGE_MIN_THRESHOLD_ADDRESS`, `VOTING_TO_CHANGE_PROXY_ADDRESS`) don't seem to match https://github.com/poanetwork/poa-dapps-voting/blob/core/src/contracts/addresses.js#L11

But anyway it looks like we won't be able to update DApps now to use new json file, because they have the same source code for all networks, they would have to `$.ajax.get` json from github. Maybe there's a better way.

**Comment by vbaranov** [comment]
>OK, still some names (VOTING_TO_CHANGE_MIN_THRESHOLD_ADDRESS, VOTING_TO_CHANGE_PROXY_ADDRESS) don't seem to match https://github.com/poanetwork/poa-dapps-voting/blob/core/src/contracts/addresses.js#L11

Right, I've added `_ADDRESS` suffix everywhere to unify namings https://github.com/poanetwork/poa-dapps-voting/pull/94

Dapp updates will wait for approvement of current PR and the same for Core.

**Comment by rstormsf** [comment]
@phahulin @vbaranov I can't approve it until you guys, reach to some consensus :-) 
I guess @phahulin need to approve it if both of you have an agreement

**Comment by phahulin** [comment]
@rstormsf would you take a look or do I merge?

**Pull request merged**
